
@api-gateway=http://localhost:8081
@user-api=http://localhost:8083
@keycloak-api=http://localhost:8085

@contentType = application/json
@userId = "4c5c0000-97c6-fc34-a0cb-08db322230c0"

################################# Keycloak API #################################

###
# @name ApiRoot_Keycloak
GET {{keycloak-api}}
###


###
# @name Authenticate
POST {{keycloak-api}}/realms/keycloak-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id=booking-client-credentials
&client_secret=TRS6PC1fyAqi7oWIOgAL89d8uPvLl4NE
&scope=openid
> {% client.global.set("access_token", response.body.access_token); %}
###


### ThreadPool Stress Test
# @name ThreadPool_Stress_Test
POST http://localhost:8083/test/threadpool?count=50
accept: application/json
Content-Type: application/json
authorization: Bearer {{access_token}}


################################# User API #################################

###
# @name ApiRoot_User
GET {{user-api}}
###


###

# @name Register_User
POST {{api-gateway}}/api/v1/user
accept: application/json
Content-Type: application/json
authorization: bearer {{access_token}}

{
  "userName": "john.doe",
  "fullName": "Johneous Doeus",
  "email": "johndoe1@gmail.com",
  "password": "A93%s/foC1zxMQf-"
}
###


###
# @name Get_User_By_Id
GET  {{api-gateway}}/api/v1/user/4c5c0000-97c6-fc34-a0cb-08db322230c0
accept: application/json
Content-Type: application/json
authorization: bearer {{access_token}}
###


###
# @name Edit_User
PUT {{api-gateway}}/api/v1/user/4c5c0000-97c6-fc34-a0cb-08db322230c0
accept: application/json
Content-Type: application/json
authorization: bearer {{access_token}}

{
  "userName": "John Doe Updated",
  "fullName": "John Doe",
  "email": "john.doe@gmail.com",
  "password": "A93%s/foC1zxMQf-"
}
###


