spring:
  application:
    name: api.gateway
  threads:
    virtual:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/realms/keycloak-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/{version}/user/**
              filters:
                - TokenRelay

server:
  port: 8081
